services:
  - type: web
    name: pos-business-model
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: FINANCIAL_KPI_PIN
        sync: false
