# Generated by Django 6.0.6 on 2026-09-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_legacy_tenant(apps, schema_editor):
    tenant_model = apps.get_model("mini_mart", "Tenant")
    tenant, _ = tenant_model.objects.get_or_create(
        slug="legacy",
        defaults={"name": "Legacy workspace"},
    )
    for model_name in ("Product", "Customer", "ExistingDebt", "Sale", "SaleItem"):
        model = apps.get_model("mini_mart", model_name)
        model.objects.filter(tenant__isnull=True).update(tenant_id=tenant.pk)


def remove_legacy_tenant(apps, schema_editor):
    tenant_model = apps.get_model("mini_mart", "Tenant")
    tenant_model.objects.filter(slug="legacy").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0004_product_alternative_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='mini_mart.tenant'),
        ),
        migrations.AddField(
            model_name='existingdebt',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existing_debts', to='mini_mart.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mini_mart.tenant'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='mini_mart.tenant'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='mini_mart.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mini_mart.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_membership')],
            },
        ),
        migrations.RunPython(create_legacy_tenant, remove_legacy_tenant),
    ]
