# Generated by Django 6.0.6 on 2026-09-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0005_tenant_customer_tenant_existingdebt_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_unit',
            field=models.CharField(default='Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='units_sold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alternative_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='mini_mart.product')),
            ],
        ),
    ]
