# Generated by Django 6.0.6 on 2026-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0006_product_updated_at_saleitem_sale_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
    ]
