# Generated by Django 6.0.6 on 2026-09-17 12:24

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_alternative_units(apps, schema_editor):
    product_model = apps.get_model("mini_mart", "Product")
    unit_model = apps.get_model("mini_mart", "ProductUnit")
    for product in product_model.objects.filter(
        has_alternative_unit=True,
        alternative_unit__isnull=False,
        alternative_selling_price__isnull=False,
    ):
        unit_model.objects.get_or_create(
            product_id=product.pk,
            name=product.alternative_unit,
            defaults={
                "conversion_quantity": product.alternative_unit_quantity,
                "selling_price": product.alternative_selling_price,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0007_tenantmembership_can_view_financials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conversion_quantity', models.PositiveIntegerField(help_text='Number of base units consumed when one of these is sold.')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_units_config', to='mini_mart.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_product_sale_unit')],
            },
        ),
        migrations.RunPython(migrate_legacy_alternative_units, migrations.RunPython.noop),
    ]
