# Generated by Django 6.0.6 on 2026-09-17 13:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0008_productunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('held', 'Held')], default='held', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspended_orders', to='mini_mart.tenant')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SuspendedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sold', models.PositiveIntegerField()),
                ('stock_quantity', models.PositiveIntegerField()),
                ('sale_unit', models.CharField(max_length=50)),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mini_mart.suspendedorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mini_mart.product')),
            ],
        ),
    ]
