# Generated by Django 6.0.6 on 2026-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0009_suspendedorder_suspendedorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='financial_kpi_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
